# Generated by Django 4.0.2 on 2022-02-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('markdown', models.CharField(max_length=20000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('TRU', 'Truck'), ('SUV', 'SUV')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffmembership',
            name='buzz_list',
        ),
        migrations.RemoveField(
            model_name='staffmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuzzList',
        ),
        migrations.DeleteModel(
            name='StaffMembership',
        ),
    ]
